language: php
services:
  - mongodb
php:
    - 5.4
    - 5.5
before_install:
    - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - curl -sS https://getcomposer.org/installer | php
install: php composer.phar install
before_script: mv Tests/config/parameters.yml.travis Tests/config/parameters.yml
script: php vendor/bin/phpunit -c Tests
env:
  global:
  - secure: F4MA+wgDwWbwGtPDLv2Bgr8PnIei7D1RrtouMP7K8dTUGQylkHu6iDT7lIuvRiO+W8ILyEltT8xAteKJGpyNjaIcaAjxRfMTftvyhPQWV2mz6X1zXPeYUnLh6IcuKeDQMcHns5yhaDXjrb0p42LxNDWtR85UQkWBgloXAP3Gy30=
  - secure: WewCG622dWV2i6nWISCOMe1731FSeZ97pA6Q4E58hMlPOWsQZKFXJwKSolpGMaWQC0qtA6aa3y5fjstgGCmGFYvYjqy710L7pXW08EyrXx0CrsQYAGqpthvUBfSxEh8H9CzRX8tSwW3gAz/wOUhd+Zh/8g+CNT6EqMaxjYhybeA=
